### ISSUE TITLE
Add Popup to Search Bar

### ISSUE THREAD

**Issue by user-64bit** [arth2002/my-tweetfolio#1]
Hello There :wave: 
This is my personal portfolio website so It might feel stupid request but,
I want to add a pop-up when someone clicks on the search bar.

Pop-ups can be Jokes or Funny Images. (If you can then add a Sarcastic Image of Chandler)
Thanks for checking it out. :smiley: 

Feel Free to ask for help

**Comment by rashmisubhash** [comment]
Can I take this up?

**Comment by Bhavya0304** [comment]
Please assign me this issue. I really want to work on it. And I have also worked on this repo before...

**Comment by user-64bit** [comment]
Hey @Bhavya0304,
I'm assigning this issue to @rashmisubhash 
But if you really want to work on this project then you can work on #3 
Thanks for your help :smile: 

Don't Forget to Star :star: this Repo.
Thanks :smiley:

**Comment by anshrusia200** [comment]
I can do this. Please assign it to me

**Comment by user-64bit** [comment]
Hey @rashmisubhash 
Are you working on this issue or not?
Please tell me.
So If you are not then I can assign to someone other.
Thanks

**Comment by arth2002** [comment]
Hey @rashmisubhash 
Are you working on this issue or not?
Please tell me.
So If you are not then I can assign to someone other.
Thanks

**Comment by user-64bit** [comment]
Hey @rashmisubhash 
Sorry but because of you're inactiveness I'm gonna unassign you from this issue.

Hey, @anshrusia200 do you want to take it from here?

**Comment by anshrusia200** [comment]
Sure @arth2002 i will work on this. Please assign it.

**Comment by user-64bit** [comment]
hey @anshrusia200 
I've assigned you
Thanks for your Contributions.

Don't forget to star :star:  this repo

**Comment by anshrusia200** [comment]
I have created a PR. Please review.
