### ISSUE TITLE
Pop-ups on Buttons

### ISSUE THREAD

**Issue by user-64bit** [arth2002/my-tweetfolio#2]
So If you check out my Portfolio(tweet-folio) then you will find every piece of information is in Tweet format.
And every tweet has four buttons (comment, retweet, like, and share)

I just want simple pop-up window when someone click on button.

Pop up should Show "Thanks for Encouragement"
I've added similar pop-up on *tweet* button so you can add similar pop-up to this buttons too.
Thanks :smile:

**Comment by yuvi2565** [comment]
@arth2002 I would like to work on this

**Comment by user-64bit** [comment]
Sure Thanks For your help.

Don't forget to star :star:  this repo
Thanks :smiley:

**Comment by anshrusia200** [comment]
I can do this quickly. Please assign it to me

**Comment by Vedant755** [comment]
Can I work on the issue?
It will be the best transition for sure!

**Comment by user-64bit** [comment]
Hey @yuvi2565 
Are you working on this issue or not?
Please give some response.
if you're not then tell me I'll assign to someone else
Thanks

**Comment by yuvi2565** [comment]
@arth2002 sorry for delay. It is almost done . I will submit it shortly.
Thank you for your patience.

**Comment by user-64bit** [comment]
@yuvi2565 
No worries 
Take your time ✌
