### ISSUE TITLE
Make Interactive "connects" section

### ISSUE THREAD

**Issue by user-64bit** [arth2002/my-tweetfolio#4]
I want to make connect section on [tweetfolio](https://arthprajapati.netlify.app/connects)
 
Features:
--> when someone clicks on the tweet, It should show a pop-up that says, "This Section is still under construction but you email me on "arth.prajapati@outlook.com"
--> little bit design improvement (optional)

**Comment by Bhavya0304** [comment]
I want to work on this issue. Please if you can assign me this!

**Comment by user-64bit** [comment]
Sure. Thanks for helping

dont' forget to star :star:  this repo
