### ISSUE TITLE
Documentation: How to use this project locally.

### ISSUE THREAD

**Issue by user-64bit** [arth2002/my-tweetfolio#9]
Hey There,
I am creating this issue because the default documentation of Reactjs is not good enough for this particular project.
So the task is to create good (make it fancy if you can) documentation that describes,

--> How to install using this Project Locally (Installation Steps)

So this is a simple issue. Make it a little fancy by adding a gif of the installation steps.

**Comment by dhrumishah** [comment]
I would like to do this!

**Comment by user-64bit** [comment]
Sure, You can work on this @dhrumishah 
Thanks for your contribution.

Don't forget to star :star:  this repo
Thanks :smiley:

**Comment by dhrumishah** [comment]
> Sure, You can work on this @dhrumishah Thanks for your contribution.
> 
> Don't forget to star ⭐ this repo Thanks 😃

![image](https://user-images.githubusercontent.com/84569241/193439779-c05d8606-71bd-41f7-8e00-0c4f8e69b694.png)
I am not able to install node modules

**Comment by user-64bit** [comment]
@dhrumishah 
Use `yarn`

**Comment by user-64bit** [comment]
Hey @dhrumishah :wave: 
How's it going?

If you're having any issues, then you can freely share them with me. :relieved: 
Happy Coding :smiley: 
Thanks :+1:
